-- Generated by jwc (incremental diff)
CREATE TABLE IF NOT EXISTS "link" (
    "code" varchar(8) NOT NULL,
    "url" varchar(2048) NOT NULL,
    "hits" integer NOT NULL,
    "created_at" timestamptz NOT NULL,
    PRIMARY KEY ("code")
);
