-- Add api_call table (merged from 1kb-landing).
CREATE TABLE IF NOT EXISTS "api_call" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "path" varchar(200) NOT NULL,
    "method" varchar(8) NOT NULL,
    "status" integer NOT NULL,
    "latency_ms" integer NOT NULL,
    "ts" timestamptz NOT NULL,
    PRIMARY KEY ("id")
);
